resource "azurerm_policy_assignment" "restrict_resource_types" {
  name = "restrict_resource_types"
  scope = "${azurerm_resource_group.sentia.id}"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/a08ec900-254a-4555-9bf5-e42af04b5c5c"

  description = "Restrict resource types to compute, network and storage"
  display_name = "Restrict resource types"
  parameters = <<PARAMETERS
    {
      "listOfResourceTypesAllowed": {
        "value": [
          "Microsoft.Compute/availabilitySets",
          "Microsoft.Compute/virtualMachines",
          "Microsoft.Compute/virtualMachines/extensions",
          "Microsoft.Compute/virtualMachineScaleSets",
          "Microsoft.Compute/virtualMachineScaleSets/extensions",
          "Microsoft.Compute/virtualMachineScaleSets/virtualMachines",
          "Microsoft.Compute/virtualMachineScaleSets/networkInterfaces",
          "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/networkInterfaces",
          "Microsoft.Compute/virtualMachineScaleSets/publicIPAddresses",
          "Microsoft.Compute/locations",
          "Microsoft.Compute/locations/operations",
          "Microsoft.Compute/locations/vmSizes",
          "Microsoft.Compute/locations/runCommands",
          "Microsoft.Compute/locations/usages",
          "Microsoft.Compute/locations/virtualMachines",
          "Microsoft.Compute/locations/publishers",
          "Microsoft.Compute/operations",
          "Microsoft.Compute/restorePointCollections",
          "Microsoft.Compute/restorePointCollections/restorePoints",
          "Microsoft.Compute/virtualMachines/diagnosticSettings",
          "Microsoft.Compute/virtualMachines/metricDefinitions",
          "Microsoft.Compute/sharedVMImages",
          "Microsoft.Compute/sharedVMImages/versions",
          "Microsoft.Compute/locations/capsoperations",
          "Microsoft.Compute/disks",
          "Microsoft.Compute/snapshots",
          "Microsoft.Compute/locations/diskoperations",
          "Microsoft.Compute/images",
          "Microsoft.Compute/locations/logAnalytics",

          "Microsoft.Network/virtualNetworks",
          "Microsoft.Network/publicIPAddresses",
          "Microsoft.Network/networkInterfaces",
          "Microsoft.Network/loadBalancers",
          "Microsoft.Network/networkSecurityGroups",
          "Microsoft.Network/applicationSecurityGroups",
          "Microsoft.Network/networkIntentPolicies",
          "Microsoft.Network/routeTables",
          "Microsoft.Network/networkWatchers",
          "Microsoft.Network/networkWatchers/connectionMonitors",
          "Microsoft.Network/networkWatchers/lenses",
          "Microsoft.Network/virtualNetworkGateways",
          "Microsoft.Network/localNetworkGateways",
          "Microsoft.Network/connections",
          "Microsoft.Network/applicationGateways",
          "Microsoft.Network/locations",
          "Microsoft.Network/locations/operations",
          "Microsoft.Network/locations/operationResults",
          "Microsoft.Network/locations/CheckDnsNameAvailability",
          "Microsoft.Network/locations/usages",
          "Microsoft.Network/locations/virtualNetworkAvailableEndpointServices",
          "Microsoft.Network/locations/availableDelegations",
          "Microsoft.Network/locations/supportedVirtualMachineSizes",
          "Microsoft.Network/locations/checkAcceleratedNetworkingSupport",
          "Microsoft.Network/locations/validateResourceOwnership",
          "Microsoft.Network/locations/setResourceOwnership",
          "Microsoft.Network/locations/effectiveResourceOwnership",
          "Microsoft.Network/operations",
          "Microsoft.Network/dnszones",
          "Microsoft.Network/dnsOperationResults",
          "Microsoft.Network/dnsOperationStatuses",
          "Microsoft.Network/dnszones/A",
          "Microsoft.Network/dnszones/AAAA",
          "Microsoft.Network/dnszones/CNAME",
          "Microsoft.Network/dnszones/PTR",
          "Microsoft.Network/dnszones/MX",
          "Microsoft.Network/dnszones/TXT",
          "Microsoft.Network/dnszones/SRV",
          "Microsoft.Network/dnszones/SOA",
          "Microsoft.Network/dnszones/NS",
          "Microsoft.Network/dnszones/CAA",
          "Microsoft.Network/dnszones/recordsets",
          "Microsoft.Network/dnszones/all",
          "Microsoft.Network/trafficmanagerprofiles",
          "Microsoft.Network/trafficmanagerprofiles/heatMaps",
          "Microsoft.Network/checkTrafficManagerNameAvailability",
          "Microsoft.Network/trafficManagerUserMetricsKeys",
          "Microsoft.Network/trafficManagerGeographicHierarchies",
          "Microsoft.Network/expressRouteCircuits",
          "Microsoft.Network/expressRouteServiceProviders",
          "Microsoft.Network/applicationGatewayAvailableWafRuleSets",
          "Microsoft.Network/applicationGatewayAvailableSslOptions",
          "Microsoft.Network/routeFilters",
          "Microsoft.Network/bgpServiceCommunities",
          "Microsoft.Network/ddosProtectionPlans",

          "Microsoft.Storage/storageAccounts",
          "Microsoft.Storage/operations",
          "Microsoft.Storage/locations/asyncoperations",
          "Microsoft.Storage/storageAccounts/listAccountSas",
          "Microsoft.Storage/storageAccounts/listServiceSas",
          "Microsoft.Storage/storageAccounts/blobServices",
          "Microsoft.Storage/storageAccounts/tableServices",
          "Microsoft.Storage/storageAccounts/queueServices",
          "Microsoft.Storage/storageAccounts/fileServices",
          "Microsoft.Storage/locations",
          "Microsoft.Storage/locations/usages",
          "Microsoft.Storage/locations/deleteVirtualNetworkOrSubnets",
          "Microsoft.Storage/usages",
          "Microsoft.Storage/checkNameAvailability",
          "Microsoft.Storage/storageAccounts/services",
          "Microsoft.Storage/storageAccounts/services/metricDefinitions",

          "nada"
        ]
      }
    }
  PARAMETERS
}
